### ISSUE TITLE
Stuck at uninstall and long shutdown/restart times

### ISSUE THREAD

**Issue by Shinji200** [zeffy/wufuc#113]
Hi, 
First of all a lot of thanks for the program, is really stupid what MS did with this "unsupported" fiasco and your solution has been a great help, anyways I uninstalled previous version and installed v0.8.0.143 with the MSI recently but after that I've noticed that my PC takes a reaaally long time to shutdown or restart when previously it took mere seconds, I'm on Windows 8.1 x64 and the O.S is installed on a SSD, the boot time takes mere seconds but shutdown/restart takes minutes, I get no errors that a process can't be closed or similar, it just get stuck for a very long time on the "loading" screen with the shutdown message, I suspect the svchost process is taking a lot of time to terminate or similar.

I tried to uninstall the program to test if this solved the issue however I'm unable to do it, the MSI get stuck at the  loading bar and nothing happens, tried using the .bat as well but also got stuck after pressing Y confirming the uninstall, same thing with Control Panel it doesn't get pass the "Preparing for removing" screen, I've left the uninstallers running for almost half hour without any results so now I'm also unable to remove the program, is there a way I can safely remove the program manually? deleting registry keys or similar?  

I tried to get some logs but couldn't find any, Event Viewer doesn't show anything useful so I hope to get some help on this issue, btw this is the only change I've made to my PC, no other programs have been installed or removed.

Thanks and regards!

**Comment by loikki** [comment]
Thank you very much for your work Zeffy!

I have the same problem than @Shinji200  (W 8.1 Pro x64 with a Kaby Lake i7-7700) and have been able to solve it by using wufuc v. 0.6.1.22

Best,

**Comment by Shinji200** [comment]
Well after some tries I managed to uninstall latest version using the .bat file, and after that my PC again took seconds to turn off or restart. I reinstalled version v0.8.0.143 using the .bat file and issue started anew, I can install updates but  Windows Update takes some time to, how to explain this mmm, "transition" between the click in Control Panel to the actual screen to search, download and install the patches. 

Also after translating the Readme and contributing files I noticed I missed to add some info :p my wuaueng.dll version is 7.9.9600.18696 and SHA-1 is 008AC846E12E033C5742668308A1489BF825F500

Sadly still couldn't find any logs but seems the only path I have for the program is C:\ProgramData\Microsoft\Windows\Start Menu\Programs\wufuc and only a couple of internet and uninstall shortcurts are present, is this the default installation path? couldn't find any on Program Files or Program Files (x86), I installed the x64 version btw.

Hope this information is helpful, I can provide some logs if I someone can tell me the correct path to where they are stored.

Regards!

**Comment by zeffy** [comment]
@Shinji200 @loikki Thank you both for reporting this. If you need to manually remove wufuc and the uninstallers are failing, you can follow the instructions at the following link, but if you can log into your desktop you can just skip to step two and open `regedit` from the start menu -> https://github.com/zeffy/wufuc#what-to-do-if-you-get-stuck-on-a-black-screen-with-just-a-cursor-after-the-windows-boot-animation

If you can recall, do you know if an elevation prompt opened when you were trying to uninstall? Sometimes the installer can hang for a bit before it opens the prompt in a minimized window in your taskbar. However it is very weird that the batch installer wasn't working, did it say anything at all after you pressed Y?

There are no physical log files kept currently due to some limitations with the new method used in 8.0, I'm currently working on implementing that. As noted in the 8.0 release notes you can use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) to view wufuc's log messages live (you need to check the Capture -> Capture Global Win32). But if wufuc is causing you issues on your systems I suggest you leave it uninstalled for now. I'll look into this.

@Syping did you encounter anything like this while testing on Windows 8.1, or can you reproduce it?

**Comment by loikki** [comment]
Every time I was trying to get the admin right, it seems that the program crashed (not only wufuc, any program). The only way I found was to reinstall W8

**Comment by zeffy** [comment]
Oh jeez, that's really bad... it must be causing a svchost to crash that is responsible for opening `consent.exe` (the UAC prompt). I'm putting this on top priority, but I need to figure out how to reproduce it since it apparently isn't happening with everyone.

Also, if this happens to anyone else, if you follow the instructions that I linked above and boot into safemode, it temporarily disables wufuc until you reboot again, so you should be able to follow the rest of the steps to disable it without having to reinstall Windows.

I'm really sorry this happened. Is there any other information you can give me, like is this Windows 8.1 x64 or x86? Did you install wufuc on a clean machine or was there other software also installed? Any updates installed before wufuc? Anything that comes to mind that could help me reproduce this in a test environment.

**Comment by Shinji200** [comment]
Hi, in my case right now I managed to uninstall wufuc with the .bat file, I ran it with admin rights, the first time it took around 30 mins to complete the uninstall process however when I used the MSI I didn't notice any elevation prompt opened, it just seem that kind of "timed out" as I got a message saying that the installer couldn't finish.

After that I reinstalled the latest version with the .bat again but as I said in my previous post the problem of long shutdown/restart time started to happen anew, however this time when I uninstalled it with the .bat the process was quick and the reboot to complete the process took mere seconds.

For now I don't have it installed but just let me know if I can be of some help to troubleshoot the issue.
Regards!

**Comment by Syping** [comment]
@zeffy I didn't had any issues at installing Updates etc, but i will go test some UAC based stuff next time when i boot up the VM, currently i am busy working on my web server. I will tell you when i'm going to try reproduce it.

**Comment by zeffy** [comment]
@Syping No worries! I was mostly able to reproduce this and I have a pretty good idea what is causing it now (although debugging a system that is having severe slowdowns and crashing is kind of difficult). Thank you though.

**Comment by loikki** [comment]
I have done a few tests before using the old wufuc (they all failed in the way described before):
 - On a W8.1 with an old wufuc that has been removed with an update
 - On a clean install after the updates
 - On a clean install before the updates
