### ISSUE TITLE
Can you explain how to patch file ``wuaueng.dll`` staticly

### ISSUE THREAD

**Issue by kamakuba** [zeffy/wufuc#117]
Hi, can you explain how to patch file ``wuaueng.dll`` staticly?
i see that you did some lookup on pattern ```"FFF3 4883EC?? 33DB 391D???????? 7508 8B05????????"```

**Comment by zeffy** [comment]
That byte pattern is the beginning of the function IsDeviceServiceable, from there wufuc uses the instructions in that function to find a couple other values and patches them. 

The easiest way to manually find the value to modify is to open wuaueng.dll in a debugger (either x64dbg or IDA will work for this), and load its debugging symbols to locate the function IsDeviceServiceable.

On x64 the beginning of the function looks like this:

```
000007FEE32BF2E4 | FF F3                 | push rbx                             |
000007FEE32BF2E6 | 48 83 EC 40           | sub rsp,40                           |
000007FEE32BF2EA | 33 DB                 | xor ebx,ebx                          |
000007FEE32BF2EC | 39 1D 56 F6 23 00     | cmp dword ptr ds:[7FEE34FE948],ebx   | ; notice here
000007FEE32BF2F2 | 75 08                 | jne wuaueng.7FEE32BF2FC              |
000007FEE32BF2F4 | 8B 05 52 F6 23 00     | mov eax,dword ptr ds:[7FEE34FE94C]   |
```

If you want to statically patch wuaueng.dll, you need to change the byte pointed to on the third line at `7FEE34FE948` from `01` to `00`. On my machine this value is located at file offset `26C948`, but it varies by version.

I recommend against manually patching because whenever wuaueng.dll gets updated your patched version will get replaced and you will have to repeat the entire process again, and if you ever run a sfc scan wuaueng.dll will be restored to its original state. 

You also have to deal with permissions issues and such, but you can check out the source code on my old branch if you want to know how to do this correctly: https://github.com/zeffy/wufuc/blob/old-kb4012218-19/patch_scripts/aio/aio-wuaueng.dll-patch.bat#L153-L168

I hope this helps. Let me know if you have any other questions or need something clarified.

**Comment by kamakuba** [comment]
Thank you for great explanation!
![01](https://user-images.githubusercontent.com/21278920/32619017-7a11ecf8-c58a-11e7-836e-7ab76580d57a.jpg)
My resulting offset same as yours...
![02](https://user-images.githubusercontent.com/21278920/32619018-7a48f8a6-c58a-11e7-8c39-d369ac75552c.jpg)

**Comment by ZURYB** [comment]
Thanks for explaining. I have described how I did it using x64dbg, perhaps it's useful to someone:

Copy `wuaueng.dll` to a work directory. From x64dbg, `Open`, select file `wuaueng.dll`. Click tab `Symbols`, and at the left section, right click `Load library` and select `wuaueng.dll`. This should be one of the modules in the list. Then right click and `Download Symbols for All Modules`.

At tab Symbols, search for `IsDeviceServiceable` and double click the line. Back to cpu tab, right click the 4th line.  `Follow in Dump`, click `Constant: ..` and look at dump1 and notice '01' is selected. Right click this byte, `Copy`, `File Offset` copies the location in the file to the clipboard. The location (in my case `26C948`) is where byte 01 needs to be changed to 00.
x64dbg can patch the file, this can be done by first creating the patch and using `Patch File` on a copy of `wuaueng.dll`.
