### ISSUE TITLE
How to install other language/MUI on 7th cpu?

### ISSUE THREAD

**Issue by daidaiworm** [zeffy/wufuc#118]
# How to install other language/MUI on 7th cpu?

I'm using 
- win7 ultimate x64
- Chinese language(The only language installed)
- Intel i7-7550U

Actually I don't care about those windows updates/hotfix. It's not very hard to install those via 3rd party anti-virus software. But I do have a need to change MUI to English and Japanese for my work frequently.

In the past it's very easy, I got several ways to do that.
- win7 integrated update
- win7 command line, run lpksetup
- using vistalizator
I guess it's due to microsoft's blocking on 7th cpu. I tried and failed all the 3 ways on my new laptop.

I've tried both version of 0.7.0.58 and 0.8.0.143. After installed that, I can find all foreign languages listed in the update dialogue. But I failed install any one kind of languages, including the most need English language, and I always got a 80073701 error.

Any clue to solve this issue? I'm quite sure the MUI/Language pack setup file are total genuine.

# FYI, Chinese, English, Japanese, German language pack download links: 

## win7 x64 - Chinese
http://download.windowsupdate.com/msdownload/update/software/updt/2011/02/windows6.1-kb2483139-x64-zh-cn_2c1884b4fdf6c8e91986369d88bbcaae01c6f187.exe
## win7 x64 - English
http://download.windowsupdate.com/msdownload/update/software/updt/2011/02/windows6.1-kb2483139-x64-en-us_9b9c8a867baff2920507fbf1e1b4a158572b9b87.exe
## win7 x64 - Japanese
http://download.windowsupdate.com/msdownload/update/software/updt/2011/02/windows6.1-kb2483139-x64-ja-jp_aeaf7e9b0b6c2173bf757330017a7f655f1f8715.exe
## win7 x64 - German
http://download.windowsupdate.com/msdownload/update/software/updt/2011/02/windows6.1-kb2483139-x64-de-de_4f4ce6bd38530b4a02199172863b21a0cba13773.exe

**Comment by zeffy** [comment]
Hi, apologies for taking so long to get back to you.

It sounds like wufuc is working correctly, I believe the error code `80073701` you are getting is for some other problem. If it were blocking updates because of your 7th gen Intel CPU it would have error code `80240037`. 

However, after some searching around on the internet, I found this: http://blogs.technet.com/b/asiasupp/archive/2011/06/20/how-to-resolve-the-error-0x80073701-error-sxs-assembly-missing-when-you-are-installing-a-service-pack-or-hotfix.aspx

I hope that helps, but unfortunately I don't think I can be much more help with this, as it appears to be unrelated to wufuc.
