### ISSUE TITLE
Can't install or activate Microsoft Update

### ISSUE THREAD

**Issue by eliminatrix** [zeffy/wufuc#125]
Hi There,

I just built a new computer with a Core i3 7100 CPU. I've installed Windows 7 x64 and all the drivers etc. I installed your patch and it seems to work - I can download and install all the Windows update patches. However, I am NOT able to install or activate 'Microsoft Updates.' On the main Windows Update screen, there is a link that says - 'Get updates for other Microsoft Products. Find Out More.' I click this and it opens up an Internet Explorer window - 'Get updates for Windows, Office and more.'
I tick the box - 'I agree to the Terms of Use for Microsoft Update'
I click the 'Install' button and I get an error = 'Microsoft Update could not be installed on your computer'

Error number: 0x80248015

I have tried re-installing / re-applying your patch a few times but it doesn't work. Could you help me with this please? I'm located in Australia, so the time difference will be a bit crazy!

Thanks!

Mike

**Comment by zeffy** [comment]
@eliminatrix Hi, unfortunately this is being caused by something other than my patch. Did some searching around and found out this article that has a couple potential solutions (posted today) https://www.bleepingcomputer.com/news/microsoft/windows-7-update-giving-a-80248015-error-heres-why-and-how-to-fix-it-/

Hope this helps.
