### ISSUE TITLE
Problem with the Wufuc

### ISSUE THREAD

**Issue by CloudHaze** [zeffy/wufuc#130]
I'm running Windows 7 ultimate 64 bit, the problem is that i'm still getting the unsupported hardware
Also i Installed the  wufuc_setup_x64 <--- and problem persist, what can i do?

CPU RYZEN 5 1600
MOBO: Ab350 fatality k4 gaming

![problempersist](https://user-images.githubusercontent.com/19179554/34329456-9bf241e0-e8d7-11e7-8721-510698ef62f6.png)

![unsu](https://user-images.githubusercontent.com/19179554/34329498-6b85a1d0-e8d9-11e7-9c79-fa80544c5eca.png)

**Comment by zeffy** [comment]
Hi, sorry for the delay; I've been without a usable computer for several days.

It's hard to tell without the log files (in your screenshot, `wufuc.rundll32.exe.log` and `wufuc.svchost.exe.log`), but this is **probably** caused because your Windows Update service is configured in a weird way. Can you run `sc queryex wuauserv` in a command prompt window and copy the output here? And upload the log files I mentioned previously.
