### ISSUE TITLE
Dr.Web neutralized

### ISSUE THREAD

**Issue by bklyn459** [zeffy/wufuc#136]
Running Win7 Pro 64-bit on Ryzen 5 wanting to eliminate the unsupported message from MS.  Ran wufuc_setup_x64 successfully.  Within a minute Dr. Web reported wufuc.dll as a threat identified as "DPH:Trojan.Inject.3" and moved the file.  Within seconds of that, MS issued the unsupported message.

I am writing to Dr.Web as well and will report back if any response.

**Comment by zeffy** [comment]
It's just a false positive. Unfortunately wufuc has to use a technique that is commonly utilized by various malware called dll injection in order to modify the process that Windows Update runs in and disable the CPU check. 

Your antivirus is simply doing its job, however in this case you can safely make an exception for wufuc.dll and let it work.

**Comment by UnbreakCode** [comment]
True :) it's not a Virus ^^

**Comment by bklyn459** [comment]
OK thought something like that, will do, thank you.
