### ISSUE TITLE
wufuc v0.7.1.81 no longer working on AMD Ryzen + Windows 7 x64

### ISSUE THREAD

**Issue by jabcreations** [zeffy/wufuc#137]
It appears as though wufuc v0.7.1.81 is no longer working with AMD Ryzen + Windows 7 x64. I did a repair and I'm not quite sure if it's disable, then check and then enable or not though either way it doesn't seem to work.

Also I'd like to talk with the author in private about a type of vulnerability that they really should be aware of and address that is not security related but still very important.

**Comment by ZockerFloh7** [comment]
I got the same Problem.
@zeffy can you maybe do an update?

**Comment by zeffy** [comment]
>Also I'd like to talk with the author in private about a type of vulnerability that they really should be aware of and address that is not security related but still very important.

@jabcreations you can [contact me on Telegram](https://t.me/fuckupsomesemicolons) to discuss this.

**Comment by jabcreations** [comment]
@zeffy Do we use the disable first or the enable first? Also we uninstalled (or repaired, can't remember offhand) and it still didn't work (after trying it both ways) on Windows 7 x64. What should we do? I know that there are security updates for that computer being hidden by Microsoft.

**Comment by ZockerFloh7** [comment]
I just did a repair through the installer and rebooted.

**Comment by jabcreations** [comment]
@zeffy No luck on that Windows 7 x64 Ryzen system so what information would prove useful in debugging for you?

**Comment by GuzziExa** [comment]
Hello Zeffy, many thanks for sharing your excellent work!
I think that my issue can be grouped with the above. My PC runs Windows 7 Ultimate 64-bit on an AMD Ryzen 5 1600X. After installing version 0.7.1.81, whatever the browser I may be using (Firefox, Internet Explorer or Google Chrome, it hangs after some time of use (maybe 10 minutes). The problem shows up with the browser freezing and not responding. The PC refuses to restart or shut down and I have to press the power button to shut it down.
The problem appears only when browsing the Internet. Otherwise, as Windows Update keeps working OK. Please note that, having deactivated automatic updates (Windows never check for updates), I run Windows Update only manually.

**Comment by jabcreations** [comment]
@GuzziExa Seriously? Don't hijack other people's threads! Start your own if you have a different issue,

**Comment by zeffy** [comment]
Sorry for the delay in my response.

New version is coming out very soon that I think should fix this, hopefully.
