### ISSUE TITLE
CAN WE USE INTEL GRAPHICS ?

### ISSUE THREAD

**Issue by nic011** [zeffy/wufuc#142]
First of all a big thanks to all contributors in this great effort!! 

I'm on a gp62 7rd leopard (i7 7700hq) ,with win8.1 pro x64 and I can't install the Intel graphic drivers ,only nvidia ones (getting unsupported CPU error)... 
I tried several driver versions also .Is this normal ? Will I need a moded bios or something?

Tnx in advance

**Comment by tomasz1986** [comment]
The installers may use their own logic to block the installation. How about simply unpacking the package and using the Device Manager to install the driver?

**Comment by nic011** [comment]
Nope .That gives "best driver for this device already installed" or ...something like that.

**Comment by tomasz1986** [comment]
I have checked the MSI driver package, and yes, in fact, that driver does support only Windows 10. In order to even try to install it, you would have to modify the INF file (and thus break its digital signature). Even then, there is no guarantee that it will be compatible.

You may want to check http://www.tomshardware.com/answers/id-3299031/kaby-lake-graphics-630-video-drivers-windows-x64.html, and maybe do more research online for the specific hardware if the above solution does not work. Either way, you may likely need to either use unofficial/modified drivers or modify the INF files yourself to make them work in Windows 7 or 8.

This issue has nothing to do with wufuc though.

**Comment by nic011** [comment]
That link was all i needed my friend. I just grabbed the latest driver mentioned in that article ( the 4508  is latest  i think) and installed via dev. manager. Everything works as expected now .
Thanks so much ,take care !

**Comment by nic011** [comment]
That link was all i needed my friend. I just grabbed the latest driver mentioned in that article ( the 4508 is latest i think) and installed via dev. manager. Everything works as expected now .
Thanks so much ,take care !

**Comment by tomasz1986** [comment]
I am glad that I could help :wink:.
