### ISSUE TITLE
Make a list of updates to NOT install on windows 7/8.1

### ISSUE THREAD

**Issue by AQXT1000** [zeffy/wufuc#143]
Could you or someone here make a issue pointing what updates to NOT install on windows 7/8.1? Because it could be really useful for anyone wanting to install updates but being aware of the updates that causes the popup window or BSODs, making a list here or in the main page would be really helpfull for everyone.

PS:I didn't know where to put this request since it's my first time here, so if you judge that it do not belong here you can delete it or ask me to do it myself.

**Comment by mirh** [comment]
You mean for BSODs like [this](https://www.askwoody.com/2018/macrium-reflect-triggers-bsod-on-32-bit-win7-systems-after-installing-kb-4088875-this-months-monthly-rollup/)?
Or am I missing something older and more nefarious?
In that case there's already [a list](https://www.askwoody.com/patch-list-master/) (it's monthly because I think for such issues microsoft get their asses up after some time)

As for the "popup window".. Are they still a thing now that free W10 update campaign ended?
Or do you mean telemetry?

**Comment by zeffy** [comment]
@mirh specifically we're referring to the updates released since the Spectre/Meltdown vulnerabilities were discovered that have caused widespread system instability and crashes. at first I was thinking that my patch was marking "incompatible" updates as "compatible" as a side effect of how it works and it was causing updates to be installed on PCs they shouldn't have been, but I think from what I've seen since then it appears to have just been Microsoft releasing buggy updates and didn't have anything to do with wufuc. But if this trend continues, I think it would be a good idea to have a list of "bad" updates that are known to cause problems.

**Comment by danielsokolowski** [comment]
I would humbly suggest against that, if 'wufuc' was determined not to be the cause (and assuming it never will conflict with other updates) such list falls outside of this project's scope. Development resources are finate and such lists tend to get outdated once the excitement dies down.

**Comment by zeffy** [comment]
@danielsokolowski You make a good point. However, I don't think it is outside the realm of possibility that Microsoft may at some point push updates that are unstable on unsupported CPUs. Though until that is the case I think you're right in that it would probably be a good idea to avoid making update "black lists" associated with wufuc.

On a side note, since wufuc is more or less "finished" (I have no plans to change the current patching procedure other than for bug fixes and the like); I've been contemplating either adding a side feature to wufuc, or more better yet creating a separate project that will let you **permanently block** specific updates (like the infamous KB2952664 telemetry update that Microsoft has reissued multiple times, bypassing the OS's built in "hidden updates" feature). Perhaps curating an update black list would be more appropriate for a project like that?

**Comment by danielsokolowski** [comment]
@zeffy in the end it's your call fine sir :), but I believe splitting it into a separate project does make sense. Take a look at unchecky which might have some good ideas, it's a different domain but similar in spirit -  prevents installing bundled software.

**Comment by mirh** [comment]
> But if this trend continues, I think it would be a good idea to have a list of "bad" updates that are known to cause problems.

I'm not sure how the trend could continue. I mean, windows is arguably in quite worse state than years ago, but that was a way more *sensitive* matter than most other normal updates. 

>However, I don't think it is outside the realm of possibility that Microsoft may at some point push updates that are unstable on unsupported CPUs.

To their credit, I can say that having to rush + missing or uncompleted documentation (of such exoteric stuff) is quite comprehensible to eventually cause problems. 
And, even though I'm by no means buying this spectre/meltdown mass scare, issues on some percentages of population still wouldn't justify blacklisting their patches. 

> like the infamous KB2952664

Oh god, please, yes. 
I don't particularly care about telemetry, to be honest, and I initially just hide for petty reasons. 
But jesus christ am I not pissed by how many times they tried to re-sneak it in??

**Comment by zeffy** [comment]
@mirh All true. I didn't mean to fault Microsoft for the buggy Spectre/meltdown patches (too much), as I realize they were most likely feeling a lot of external pressure to get fixes for the vulnerabilities out as soon as possible, so mistakes were bound to happen. 

However, there have been other cases where they have released very broken updates besides these, so it's not really a new thing.

That said, I'm definitely going to try see if it's possible to do what I described before, and will likely make it into separate project. "wublock" maybe? hmm...

**Comment by mirh** [comment]
Take also into consideration there might already be plenty of tools doing similar things on the nazi-W10.
