### ISSUE TITLE
Unsupported hardware popups are back

### ISSUE THREAD

**Issue by VVampire** [zeffy/wufuc#156]
Hello, I have been using Wufuc since I fixed and upgraded my pc.
That would be 4 days now and I really like Windows 7 and hate the new ones, so it helps a lot.
Thank you so much zeffy for your hard work, I hope you will never stop.
However, yesterday the unsupported hardware popups came back. I really don't know why.
It was very sudden, I hope someone will know what's going on.

(I know there was one open, similiar issue, but person didn't specify enough and wasn't active for 2 days, so I don't know if person also got Wufuc working, but issue just came back or Wufuc never worked for him).

**Comment by zeffy** [comment]
Could you post your wufuc.log file from C:\ProgramData\wufuc\wufuc.log? 

Thanks.

**Comment by VVampire** [comment]
Sure, no problem.
[wufuc.log](https://github.com/zeffy/wufuc/files/1997805/wufuc.log)

**Comment by zeffy** [comment]
Looks like #146, which I have fixed in the latest appveyor builds. I have not had a lot of free time recently so I haven't been able to make a new release for it, but you can get the appveyor build here: https://ci.appveyor.com/project/zeffy/wufuc/build/job/aekpdymfywhcfh6b/artifacts

Uninstall the version of wufuc you have now and install this one, and the popups should stop appearing.

**Comment by VVampire** [comment]
Awesome, thanks for help.
I hope that will fix my issue.

**Comment by chrcoluk** [comment]
I am going to install the build now and will confirm if it works, Microsoft have coded this so it gets very aggressive if ignored, I am getting the popups almost every 20 mins right now, and they also take focus with the on top windows property.

This is bad enough that a legal letter has been sent to Microsoft from my solicitor.  As I have a fully licensed version of windows and this is malware type behaviour.  Nowhere in the original license agreement does it state Microsoft will hassle me to stop using the product for "any" reason.

**Comment by zeffy** [comment]
@chrcoluk make sure you use the [latest release](https://github.com/zeffy/wufuc/releases/latest) in GitHub releases and not the build I linked above, as this specific issue has been fixed in the latest release. There is still the possibility of the occasional popup but they will be far less frequent (usually only show up when you log in).

**Comment by chrcoluk** [comment]
Thanks, this solves my download issue as well then. :)
