### ISSUE TITLE
Behavior in virtualized environment (keeps working)

### ISSUE THREAD

**Issue by jimuk** [zeffy/wufuc#29]
I have been doing some tests to see how this updated behaves in a virtualized environment. This is because (Type 1?) hypervisors like Hyper-V expose the real CPU to the guest OS and this change should break updates on such guests. My initial finding is that updates keep working even on the latest CPUs.

Please does anyone have any ideas how this works and if it could be used as a workaround for this problem?

**Comment by zeffy** [comment]
I'm not entirely sure, I don't actually have a kaby lake/ryzen cpu, so I run my tests inside VMware with custom `cpuid` settings that trick the check and make the message display. So I couldn't say what the behavior is in a VM when you have the real thing. I've seen several people across the web saying that their updates are still blocked in VMs, though, so maybe it is a fluke?

However, if you look at the [pseudo-C](https://gist.githubusercontent.com/zeffy/e37e8ffde3794b97ecffc46c0a428f55/raw/3d94affe3fb08cc8f30c4e9befc5d22c397269f2/2017-05-18_16-09-13.txt) for `IsCPUSupported`, you'll see it does indeed check the hypervisor leaf `0x40000003`, so maybe that has something to do with it?

**Comment by zeffy** [comment]
And in regards to your final question, yes you may be able to download and install updates in a virtualized environment but you won't be able to install them on the host, because the check is built into the core windows update engine, and I believe it gets run regardless of how you try to install the updates (i.e. WSUS Offline, .msu packages, or directly through Windows Update).

I've seen people doing the reverse of what I'm doing, and spoofing a cpuid from an older CPU so that they can install updates in their VM again, so I think others have probably already tried what you are thinking.

**Comment by jimuk** [comment]
I have now tried this with both Windows 7 32-bit and 64-bit running in Hyper-V. In both cases all updates installed okay and Windows update continues to work. Looking at the pseudo-code (I am not an expert on CpuID at all) it seems, as you said, IsCPUSupported checks for a hypervisor and then returns True.

This makes complete sense because otherwise it would mean legacy operating systems could no longer be run as guests on modern hosts. It also shows that the whole thing is a shame - Microsoft are not doing this for technical reasons but for commercial reasons. It can only be matter of time before someone reports them to the anti-trust authorities for this abuse.

In the meantime this may present a method to workaround this problem without patching any code. No doubt this will then become a game of whack-a-mole as MS change the code again.
