### ISSUE TITLE
Investigate cleaner solution that doesn't involve patching system files

### ISSUE THREAD

**Issue by zeffy** [zeffy/wufuc#4]
I realize these scripts are not that user friendly. When I made them, I never anticipated this project blowing up like it has. 

So moving forward, I'm going to look into simplifying the process, possibly with some kind of Windows service that can patch wuaueng.dll in memory without actually modifying any system files, much like how [UxStyle](https://github.com/riverar/uxstyle) works. This would be much safer and also enable other possibilities that would otherwise be impractical with the xdelta/batch script setup I have now.

If any of you have any ideas regarding this or want to help, feel free to comment!

**Comment by Titokhan** [comment]
Hi there!

You may know that Microsoft closed a loophole that exists in KMS V4 & V5 protocol which allows activation against a locally emulated KMS activation server.

KMS V6 patches it, but after examining the related files (especially SppExtComObj.Exe i.e the KMS Connection Broker) the blocking function is found and can be easily patched.  
  
But the problems are:
1. It needs to be re-patched after each update that patches the file(s).
2. SFC errors will occur as the health of the image is tampered.
3. Due to the strict requirement of driver signing, a signed service isn't  a feasible solution although it is viable.  
  
Some interested people (including me) came up with a solution that involves exploiting [the inherent debugging options](https://msdn.microsoft.com/en-us/library/a329t4ed(vs.71).aspx). If you're interested, we can start collaborating.

**Comment by zeffy** [comment]
Hey, that sounds like a neat idea! I've had to use those image file execution options before for other projects, so I'm familiar. 

Although I'm not sure if it would be a solution in this particular use-case, because wuaueng.dll runs inside of a svchost.exe, along with a few other services. I would love to be proven wrong, though! 

How would you like to collaborate?

**Comment by Titokhan** [comment]
Regarding the Service Host part - ya, I got that. I did some digging on my own too, found the string but unable to make the patch due to lack of knowledge in reversing. Thanks for your contribution and intention to open source it.  
  
Regarding collaboration, can it be possible to contact you via any IM (like Telegram/Signal)? Gitter is much bloated!

**Comment by levicki** [comment]
@zeffy Did you perhaps check why IsCPUSupported() function is also checking Hypervisor leaf 0x40000003? I didn't have time to check the code in more detail but maybe it does more than just returns 1 or 0?

**Comment by zeffy** [comment]
@levicki As far as I could tell in my initial analysis of IsCPUSupported(), it just compares the values of the registers set by the `cpuid` instruction to see determine what CPU features are present, etc. But I admit my knowledge of this instruction is limited, so I'll look into what you're talking about.

And yes I am aware, however patching directly to `C:\Windows\System32\wuaueng.dll` should make no difference, correct? It should still patch the right file, unless I'm missing something?

If Microsoft starts digitally signing wuaueng.dll, I'll just have to fast track this issue and get an in-memory patching solution finished. However I am skeptical whether they will actually bother to do this, as other commonly patched files like uxtheme.dll are still not signed.

**Comment by neva78** [comment]
Hi,
My name is Nick Heath and I am a  reporter with TechRepublic.com. Sorry to contact you in this manner. 

I wondered if you'd be willing to comment on why you produced this patch and your thoughts on Microsoft's rationale for introducing the IsCPUSupported() check, which [it said at the time](https://blogs.windows.com/windowsexperience/2016/01/15/windows-10-embracing-silicon-innovation/#OUvCuFwjQJM1OApr.97) was related to:

"For Windows 7 to run on any modern silicon, device drivers and firmware need to emulate Windows 7's expectations for interrupt processing, bus support, and power states- which is challenging for WiFi, graphics, security, and more."

Also I was wondering how confident you are that Microsoft won't make changes to block this workaround?

My email is nick.heath@cbsinteractive.com.
Many thanks,
Nick

**Comment by gkeizer** [comment]
Hey Zeffy,

Gregg Keizer, reporter with Computerworld here.

I'd like to connect for a short interview on what you've done to patch Microsoft's blocking of WU to select silicon. Prefer phone chat but can do email Q&A as well.

You can reach me here:

gkeizer@computerworld.com

Thanks much. Look forward to hearing from you.

/keizer

**Comment by levicki** [comment]
@zeffy If you patch the file as it appears in `C:\Windows\System32` folder, the patch will actually be done to a file somewhere in WinSxS folder and the path to that file will be different depending on the wuaueng.dll version. That means that restoring non-patched DLL version to `C:\Windows\System32` may end up overwriting wrong version in WinSxS if the link has changed in the meantime, and corrupt your component store by mixing up versions which could affect the OS servicing capability.

@Titokhan I suspected as much but it was late here and I was too tired to do a full analysis.

**Comment by zeffy** [comment]
@neva78 @gkeizer I'm not interested in doing any interviews, sorry.

---

@levicki Right, I see what you're saying now. I believe xdelta3 does a basic file size(?)/checksum comparison to check whether or not the file you are trying to patch (or restore, in this case) is the right one. So unless the file size between two versions is identical, I think the risk of corruption is relatively small, unless someone tries to manually restore wuaueng.dll after they've updated. Regardless, do you know of any way that I could account for that in the patching logic? If so, I would be greatly appreciate it.

While I'm figuring out an in-memory patching solution (which would completely circumvent this issue), I am probably going make a C# winforms app much like UXTheme Multi-Patcher, which could include more advanced version/file hash comparisons to ensure you are trying to modify the correct file. Would that work?

For now, do you think I should include a note or warning somewhere explaining there may be a risk of corruption?

Thanks for your input!

**Comment by gkeizer** [comment]
Hey Zeffy,

Sorry to hear that...but understood.

/gregg keizer, reporter
computerworld

**Comment by neva78** [comment]
No problem, thanks for replying.

**Comment by navossoc** [comment]
For me, it is kind funny see how Microsoft processes are really well protected and other 3rd party applications can't be.

I think you can accomplish your goal this way:

## Get access to that process memory
For now, the only way I see you can get access to svchost.exe (wuauserv) will be with a kernel driver. This will not be a big problem, since the [new signing requirements](https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/) applies only to Windows 10 build 1607 or newer. So all you will need is a code signing certificate that can be used to cross sign your driver.

## Wait until the DLL is loaded into memory
You can do that using something like [PsSetLoadImageNotifyRoutine ](https://msdn.microsoft.com/en-us/library/windows/hardware/ff559957(v=vs.85).aspx), just set up the notification and wait for it on the right process.

## Search the function address
a. You can use some `signature ` to figure out the area where the function is and then you can use something like [udis86](http://udis86.sourceforge.net/) to disassembly a few nearby bytes to get the correct starting address or;
b. You can try to download the public symbols for `wuaueng.dll` and get the proper address of the function, but I'm not sure when these symbols will be available to public and that will be a problem.

**Note:** You can write a helper application (user mode) just to figure out the address, then you send that address back to the driver and patch it.

## Patch the function
Just write a simple function that returns what is expected and it is done. Exactly like you are doing now.

**Comment by zeffy** [comment]
Awesome explanation @navossoc, thank you! I've never written a kernel-mode driver before, so this really helps point me in the right direction. Definitely will look into this ASAP. I would much prefer this solution, as maintaining a huge list of xdelta files and a kludgy batch file is getting to be pretty exhausting.

**Comment by navossoc** [comment]
@zeffy No problem...
If you have some background on C/C++ you can learn without too much difficulty.
It have some caveats, but you will learn to manage it 😎 

I'm no expert either, but if you want to follow that path and need a few more guidelines, just drop me a email and I can help you.

Cya.

**Comment by ph0sec** [comment]
@zeffy, @navossoc the driver solution is not really advisable because of the introduced overhead with the signing and possible stability/vulnerability issues. 

Try to investigate hosted service direction. If I understand correctly from your explanation, the target dll is loaded into svchost service hosting process. What you can do is write your own service dll and register it as an appropriate service [ [one](https://blog.tanium.com/back-basics-detecting-malicious-windows-services-tanium/), [two](https://en.wikipedia.org/wiki/Svchost.exe) ] in the registry. This will load your service dll into desired svchost process address space where you can continue with @navossoc suggestions (Search the function address).

**Comment by navossoc** [comment]
@ph0sec Sure, if is really that easy to gain access to `svchost.exe`, why not? Forget about the driver.
You should try to write a dummy service, just to see if you get inside the same process context.

But hey, again, for this work you need to modify `netsvcs` on
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SvcHost`
Right?

For now, seems that registry key doesn't need any special user to get access.
It may break again on future too, anyway, for now it's a cleaner solution.

I'll read that blog post later...

**Comment by zeffy** [comment]
Wow, even better! That's a brilliant approach @ph0sec. I'll start looking into this as soon as I get some lingering bugs in the batch script ironed out. I can't even begin to say how much I appreciate all of your feedback and ideas!

**Comment by jspraul** [comment]
https://0patch.com/ intends to enable this type of functionality commercially.

https://news.ycombinator.com/item?id=13783004
> Micropatches only live in memory, they die with the process. They don’t change file system and installed product

https://news.ycombinator.com/item?id=13782830
> we don't support kernel mode at this moment

Not sure how they as a commercial entity would treat a modification like this one, and not sure whether or not they would ever share the exact excruciating details of how their implementation works. (Also not sure whether or not Windows Update could be bypassed entirely user mode somehow.)

**Comment by ph0sec** [comment]
@zeffy @jspraul hope you understand that no matter what is done here, it will not be permanent just for a while. To truly make it more lasting there is much work to be done at the much lower level:

- you probably will need to control cpuid 
- you'll need to control all aspects of windows versioning to make it look like the contemporary win 10 in terms of registry, telemetry, etc
- don't forget about new tech (hypervisor based) which was introduced into win 10. You can just check if it's present to understand what version is really running on the machine.

The possibilities are limitless to prevent you from getting updates. 
So, treat this PoC like a funny project to gain knowledge and fun :-)

**Comment by levicki** [comment]
Guys, kernel mode drivers on x64 OS since Windows XP 64-bit require cross-signing with kernel-mode code signing certificate. The cheapest such certificate is $220/yr with DigiCert, and you have to submit passport photo, proof of residence, and sign the contract in front of the laywer -- I happen to know because I own one such certificate.

Any driver written with an intent to mess with other processes would quickly get reported to Microsoft and certificate would be blacklisted and revoked. Sorry to rain on the parade but that's just how things work on Windows platform.

@zeffy You would probably need to examine the hardlink in order to figure out what it is pointing to in the moment of restore and whether that is the same as what it was pointing to at the time of backup. If it is not the same then it is not safe to restore because the version might be newer (or even older if user uninstalled some hotfix). Maybe the best approach would be to warn users and let them deal with it.

**Comment by navossoc** [comment]
> Any driver written with an intent to mess with other processes would quickly get reported to Microsoft and certificate would be blacklisted and revoked. Sorry to rain on the parade but that's just how things work on Windows platform.

@levicki Hahahha, say that shit to Cheat Engine...

[]'s

**Comment by 1n5aN1aC** [comment]
@navossoc Does cheat engine use a kernel-mode driver?

I don't know much about the protections of the core system itself, but I highly doubt cheat engine would need a kernel-mode driver just to play with the memory of other user-mode processes...

**Comment by navossoc** [comment]
@1n5aN1aC Yes, they have one...

https://github.com/cheat-engine/cheat-engine/blob/master/DBKKernel/DBKDrvr.c#L155

http://wiki.cheatengine.org/index.php?title=DBVM

**Comment by 1n5aN1aC** [comment]
@navossoc Huh, TIL.  Very interesting and cool that it can do that.

**Comment by levicki** [comment]
@navossoc 

First, no need to be rude. Second, cheat engine is not messing with Microsoft processes but with user's game processes. The moment you start using things like that on core OS functionality to circumvent Microsoft's protections is the moment it gets attention and gets blacklisted.

Moreover, it seems that in VM mode it crashes (and the probability of crashing increases with number of CPU cores) -- it says right in the Wiki you linked. That means it is not stable enough for daily use.

**Comment by navossoc** [comment]
@levicki Sorry mate, I was not trying to be rude, but what you said sounds like a joke to me. Just that, so don't take me wrong.

There are a few examples like: anti rootkit tools and Anti Virus that bend over the OS and circumvent many protections for their own purposes.

Also @zeffy showed here UxStyle as an example of bypassing Windows protection with a driver.
And hey, it is still there, still working... No one cares.

The world would be a better place if things really work like you said.
Cheers.

**Comment by levicki** [comment]
@navossoc What I am saying is that anti-rootkit and anti-virus have a (for Microsoft) beneficial purpose. UxStyle patching is for visual change and is benign. That couldn't be said for Windows Update patching.

Don't get me wrong, such patching can certainly work for a while. But what happens when Microsoft adds CPU check is in every update executable including signed ones? I don't like Microsoft or their behavior, but crippling or even outright disabling security by running kernel mode drivers which leave your system wide open just to enable getting new security patches doesn't make sense for me.

Instead I would prefer if someone with Kaby Lake started class action suit against Microsoft. People paid $200 for support, and support has now been cut off 8 months before the end of mainstream support, not to mention there is also extended support for few more years after that where Windows 8.1 should still be getting at least security updates. I have read Software License Agreement and nowhere does it say that they have the right to revoke support earlier.

I protested Microsoft's sleazy move on [Intel's forum](https://software.intel.com/en-us/forums/intel-isa-extensions/topic/731318), because basically both Intel and AMD remained silent and allowed Microsoft to tell their customers how Ryzen and Kaby Lake are essentially not compatible with Windows 8.1 (I know it says "not supported with Windows 8.1", but to me that is the same if they are actively preventing you from trying to run the software.

All this is setting a very bad precedent in software and hardware industry and I really hope some lawyer will pick this up and start a class action, they all deserve to be crucified for this.

**Comment by zeffy** [comment]
@levicki Regarding the restoring of backups, when you "uninstall" the patch, the script actually just uses another xdelta patch to revert the changes, it does not use the .bak created during the install procedure. That backup is simply created in case something disastrous happens, such as wuaueng.dll getting corrupted and thus unable to be patched/unpatched.

So using the script to unpatch, even after installing or uninstalling updates should not break anything. It will simply fail if it can't find the correct xdelta file to use, or if wuaueng.dll is the wrong version (because as I said, xdelta includes file size/checksum verification).

However I agree there should be some kind of warning regarding the manual restoration of the .bak files, I will add this into the next release.

**Comment by Diazonium** [comment]
The whole driver signature deal is overblown, you can simply use DSEO to override signature enforcement. ( http://www.techspot.com/downloads/6205-driver-signature-enforcement-overrider.html )
The desktop watermark from test mode can be disabled by this: https://deepxw.blogspot.hu/2008/12/remove-watermark-v03-build-20081210.html

**Comment by zeffy** [comment]
@Diazonium Yes, I know about those tools. But I don't think it's a good idea to make users have to run a bunch of other software just to get this patch working. The goal here is to make it process quick and simple, and not scary for novice users. 

I've been doing quite a bit of research on hosting my own service under wuauserv's svchost.exe in order to access its address space for patching, and it all seems very promising. It shouldn't be too difficult, just time consuming.

**Comment by levicki** [comment]
@Diazonium The point is that once you disable signature enforcement you are an easier target for malware. The whole thing zeffy is doing is to improve security by enabling hotfix installation, not reduce it.

**Comment by Diazonium** [comment]
@levicki Fair enough, although if no other viable solution is found, I would argue that loosing driver signature enforcement is a lot less of a security hole, than having a bunch of actual unpatched vulns.
After all, installing a new driver either requires multiple exploits, or convincing the user to run a malicious file as admin (if they do that, it is already pretty much a lost cause).

**Comment by fre4kyC0de** [comment]
What about using cdb.exe?
https://github.com/fre4kyC0de/WindowsUpdate_KabyLake_Ryzen_Patch [check the OnTheFly-branch]

The only problem of this implementation might be WU checking the CPU on reboot.

**Comment by zeffy** [comment]
Hey there @fre4kyC0de, I actually saw your patch a while ago! It seems like a pretty interesting approach, and it's cool to see other developers are interested in this issue.

However, I would like to not require that people have to install additional software (in this case Debugging tools for Windows) in order to keep the process as simple as possible, and redistributing cdb.exe along with the patch is simply not an option due to its EULA restrictions.

I had been waiting to move forward with working on an in memory patching solution until I could see what Microsoft's reaction to my patch was, and if they were going to add in additional checks or other forms of obfuscation. It doesn't appear that they have done any such thing, however, so I will start moving forward with this again.

**Comment by zeffy** [comment]
Another update, after trying to get my own service to run in the same memory space as wuauserv, I didn't have much luck, as most of the resources ([1](https://web.archive.org/web/20040206042331/http://www.binglesite.net:80/article/svchost_dll_service.html), [2](https://forum.sysinternals.com/writing-a-service-that-runs-under-svchost_topic11974.html)) I found were pretty old, and I don't know if the methods even still work in Windows 7, let alone 8.1. There still may be a way to get this to work, but for now I'm investigating another method.

Right now I'm looking into creating a custom task that runs a small, short-lived patcher exe as `NT AUTHORITY\SYSTEM` (this will give it access to `svchost.exe`'s memory space) whenever `wuauserv` starts, and immediately patches its memory to disable the cpu check. In theory this should work great, but I need to get the code finished and to test it thoroughly.

**Comment by fre4kyC0de** [comment]
As soon as I have some time, I'll try to create a downloader script, which automatically downloads cdb.exe...

**Comment by zeffy** [comment]
The method I came up with works! I just need to fix a couple things and make an installer. Not sure how long that will take, though.

Without patch:
![vmware_2017-05-29_18-57-30](https://cloud.githubusercontent.com/assets/10877719/26565575/299f85e2-44a1-11e7-8954-614416315c0b.png)

With patch:
![vmware_2017-05-29_18-57-06](https://cloud.githubusercontent.com/assets/10877719/26565580/2e0c8c74-44a1-11e7-8446-05ac2babbfb7.png)

**Comment by levicki** [comment]
I just had some time to start reverse-engineering wuaueng.dll on my own to look at what Microsoft is doing.

In my version of the file (which is currently 7.9.9600.18628), there are some additional venues worth exploring:

There is a function `AreTestKeysAllowed()` which upon returning true enables a check for the registry key `SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Test\Scan` which can contain a REG_DWORD `ForceUnsupportedCPU` to allow for an override of the CPU detection function result.

The function `AreTestKeysAllowed()` is looking at a flag set in `DllMain` (to false) and in `CSusTestHook()` class depending on the result of the function `IsValidAUTestCabFileText()`. The contents of the file are compared with the Unicode string `Windows Update Test Key Authorization File\r\n`, and also a file timestamp is checked (haven't analysed that part yet).

To me it appears that if we manage to get a hold of a properly signed test cab file with said contents we may be able to override the "unsupported" CPU check via registry key and without patching.

**Comment by zeffy** [comment]
@levicki I looked into this already a while back. It's not really practical because you would have to trick WinVerifyTrust, plus it could enable other potentially security compromising registry test flags as a side effect as well, which seems undesirable. A better approach would be to `nop` out the call to `AreTestKeysAllowed()`, only for the `ForceUnsupportedCPU` flag, which is what my 2nd approach was in the writeup.

My new in memory patching method is pretty much done, and works amazingly. I'm learning WiX so I can make a proper MSI installer and satisfy #9.

**Comment by levicki** [comment]
@zeffy I was not aware there are other compromising flags? Can you perhaps share the details? As for tricking WinVerifyTrust, you should be able to use your own self-signed root certificate.

**Comment by levicki** [comment]
@zeffy I tried using self-signed certificate. I can confirm that cannot work because Microsoft is using certificate pinning in the code, and even though I generated valid certificate which includes eku `1.3.6.1.4.1.311.76.6.1` (Windows Update) it refuses to trust the certificates not matching SHA1/SHA2 signatures of certificates of their own SubCA.

**Comment by zeffy** [comment]
Hey guys, I just released the new persistent patch with a batch script installer/uninstaller! I plan on including MSI installers in the future (#9), but it was taking too long to figure out, and I wanted to get an initial version out for testing.

I'm also rebranding the project to "wufuc" (**W**indows **U**pdate **F**orce **U**nsupported **C**PUs) with this release because the old project name was annoying to remember. The license is still GPL-3.0.

You can read more about how the new patching method works and the new features in the `README.md` file, the releases page, or check out the source code.

https://github.com/zeffy/wufuc/releases

**Comment by levicki** [comment]
Windows Update Force Unsupported CPU Kabylake? :-)

**Comment by zeffy** [comment]
Very clever! :wink:
