### ISSUE TITLE
Not an Issues (Donation) 

### ISSUE THREAD

**Issue by Kazemi-Kaze** [zeffy/wufuc#53]
not an issue but i would like to know if it's possible to sen you a few $$ as a thanks for the patch.

it really helped me and my girlfriend ☺
sorry dont know how else to contact you

**Comment by zeffy** [comment]
Wow thank you for the kind words, it means a lot! I'm very glad wufuc helped you. 

I just set up a Pledgie campaign so that you can contribute to the project if you still would like to; it's the first time I've used it before though, so if it doesn't work or you'd rather an alternative please let me know. https://pledgie.com/campaigns/34055

Also no worries, this is the correct place to contact me for anything.

Thanks again so much!

**Comment by Kazemi-Kaze** [comment]
awesome 

donation sent 

please keep up the good work ☺

**Comment by zeffy** [comment]
Very much appreciated, thanks man!
