### ISSUE TITLE
Install script isn't properly detecting Windows version

### ISSUE THREAD

**Issue by Tjazz38** [zeffy/wufuc#65]
I tried to install bug viewer, but not sure how to use. However, when I run program as administrator, it says it only works on Windows 7 x64 or x86. I am running Windows 7 Ultimate, 64 bit.

**Comment by zeffy** [comment]
Hi, sorry if my instructions before were confusing. I was trying to say you **don't** have to use DebugView since wufuc wasn't installing properly anyway.

Can you press <kbd>Win</kbd>+<kbd>R</kbd> on your keyboard, type in `cmd` and press enter, then in the command prompt that opens type in `wmic os get version` and press enter, and tell me what it says? Thanks.

**Comment by zeffy** [comment]
Never mind, I fixed it. I'm using a different command to get the windows version now that shouldn't break. I also added the option to bypass the OS version check after displaying a warning, just in case the new command doesn't work either for some reason.

Since this issue seems to be an edge case I'm not going to rush out a new release, but you can download the new build here to test it out: https://ci.appveyor.com/project/zeffy/wufuc

Please let me know if it works for you now, specifically if it correctly detects your OS version now. Thanks.

**Comment by Tjazz38** [comment]
OK, it seemed to install this time. I'll keep my fingers crossed that those messages won't appear anymore.

**Comment by zeffy** [comment]
Awesome! Glad it's working now, thanks for testing it out.

Closing this for now, please let me know if you have any other issues.
