### ISSUE TITLE
Cannot install the wufuc patch anymore

### ISSUE THREAD

**Issue by stevemoreau** [zeffy/wufuc#70]
Hi zeffy,

The popup came back these latest days, and I have just realized that no update was installed since the 13th of June.

I had successfully installed the version with wuaueng.dll in the beginning of June, and I thought I had followed the instructions carefully when moving to wufuc planned task alternative (using the utility scripts\repair_wuaueng.dll.bat script, before to load the new one - and remember there were an issue with AVG antivirus).

I have followed the [contributing](https://github.com/zeffy/wufuc/blob/master/CONTRIBUTING.md) guidelines. But as for now, I can't see the log file that you should be generated with 7.0.35.
I am having a look at the source code and WinDbg to provide you more inputs but, in the meantime, if you could suggest what went wrong please advise! Thanks

![wufuc installer - v0 7 0 35](https://user-images.githubusercontent.com/16148036/27782288-2eaca44c-5fd2-11e7-80f1-b88b9be6e20d.png)

![windowsupdatescreen](https://user-images.githubusercontent.com/16148036/27782299-385d4c58-5fd2-11e7-905c-142e72e16d35.png)

![windowsupdatehistory](https://user-images.githubusercontent.com/16148036/27782304-3d5d1706-5fd2-11e7-925c-c40a58a1933c.png)

![wuaueng dll explorer](https://user-images.githubusercontent.com/16148036/27782315-45110cb4-5fd2-11e7-8047-9c91ea73b050.png)

![wuaueng dll](https://user-images.githubusercontent.com/16148036/27782317-492f9e0a-5fd2-11e7-8be1-71f2de7230da.png)

**Comment by zeffy** [comment]
Hey there @stevemoreau,

That `wuaueng.dll_2017-06-03_19-16-16_265000_before-patch.bak` file was created by the old batchfile patch and can safely be deleted.

It's really strange that there is no log files, and it probably means that wufuc is not running at all. Out of curiosity, where did you install the wufuc files to?

What happens if you manually open Task Scheduler, right-click the wufuc task and press Run? What does it say under the Last Run Result column? Example of what it should look like:
![mmc_2017-07-03_02-54-34](https://user-images.githubusercontent.com/10877719/27787816-082260a0-5f9b-11e7-9d4f-3be3ce063199.png)

You may also want to try doing a full sfc scan by running `sfc /SCANNOW` in an elevated command prompt.

Another thing to try if you haven't already is to completely uninstall and reinstall wufuc.

**Comment by stevemoreau** [comment]
Thanks @zeffy,
I tried everything I could based on uninstall/reboot/reinstall but I had no luck.
So, I finally restored my Windows with CloneZilla, and it is now fine using directly the wufuc planned task.
I don't know what went wrong but hopefully it is behind me.
Sorry for this inconvenience,
Thanks and have a nice day.

**Comment by zeffy** [comment]
No worries, it's not an inconvenience at all!

I'm glad it is working for you now, but please let me know if you have issues again.

**Comment by CloudHaze** [comment]
@zeffy  Hello Zeffy nice to meet you i was wondering, why i'm getting this error?

I have a ryzen cpu 5 1600 with a Ab350 Motherboard + Windows 7 ultimate 64 bit

This happens when I run the file: install_wufuc as administrator.
![screenshot_2](https://user-images.githubusercontent.com/19179554/33518803-d75f04ec-d771-11e7-91dd-0ed16018cff6.png)

**Comment by zeffy** [comment]
@CloudHaze Like the error message in your screenshot says, you probably cloned the repo on accident. Download it from http://github.com/zeffy/wufuc/releases/latest either the zip or the x64 MSI file, and it should work.

**Comment by CloudHaze** [comment]
@zeffy  Thanks for your comment

Does your program, unlocks more Windows Updates? or it just Bypass the message that: Windows cannot install updates, or whatsoever?
I did install the Wufuc_Setup_x64.msi on the Program files folder
Them it open a CMD interface, and i guess that's all? right 

Sorry for my poor English. 

Because

**Comment by zeffy** [comment]
@CloudHaze My patch only bypasses the "Unsupported hardware" pop up message [(screenshot)](https://kb.stonegroup.co.uk/kb_upload/image/Windows_7_Kaby_Lake_1.jpg) that shows if you have a 7th+ generation processor. If you were getting that pop up before installing wufuc and it isn't showing now, then that means it is working.

**Comment by CloudHaze** [comment]
@zeffy  Oh i see, i never had that problem on the ryzen cpu 5 1600, i though your app unlock more updates for ryzen, i used Windows-Mini update tool, and yep i can get all updates, and install without the message (Unsupported hardware) thanks so much, anyway :3  

Now the thing is, i would love to see if someone can created a program or code that improve Single-core performance on AMD processors, because even in my cpu ryzen, i cannot enjoy games such counter strike 1.6 there is like visual lag, or poor performance...

In a 32 player servers, my pc can drop from 100 to 90... etc 
GTX 1060+ ryzen 5 cpu 1600 and rams 3200 mhz... x.x
