### ISSUE TITLE
Working so far

### ISSUE THREAD

**Issue by TGOMVG** [zeffy/wufuc#86]
I see a place for submitting issues, but not for submitting kudos. On my i5 (7th gen) new build wufuc works. I've received several Win Updates and they have successfully installed. I'm using Win7.

UPDATE
I've received several Windows Updates today and since installing wufuc. My system seems to behaving normally as well, i.e., no ill affects. Donation sent! It's worth more, but all I can do right now. Thank you, zeffy!

**Comment by zeffy** [comment]
Thank you for your kind words! I'm very glad to hear it works for you. :smile:

**Comment by ZooMSiX** [comment]
I'm with you on this.  We had a handful of laptops that were delivered to a client that can't get windows updates because if this exact issue.  The unfortunate part is the software they use doesn't work at all on windows 10 so they're completely boned..  Thanks for building this utility because it completely saved their butts!

**Comment by 1n5aN1aC** [comment]
I'm just going to add my thanks here as well.

It's working great, and it's amazing!  Thank you very much for all your work!

**Comment by zeffy** [comment]
Thank you @1n5aN1aC :)

Seeing feedback like this from users like you guys is what makes me want to keep making wufuc even better!

**Comment by 1n5aN1aC** [comment]
Although I do have one question @zeffy If I have it running and all seems good back on v0.6.1.0 (according to the dll) is there any current reason for me bothering to update my few systems running it?

**Comment by zeffy** [comment]
@1n5aN1aC I always recommend staying on the latest version (unless otherwise noted in the release notes), because I'm always fixing bugs and potential security issues. I try to be as transparent as possible in the release notes for each version so people can decide on their own if they want to update, though.

However, if you'd rather put off updating for a bit longer, there should be a new version coming out in the next few days. :)

**Comment by 1n5aN1aC** [comment]
@zeffy Thanks for the information, and the tool!
